### ISSUE TITLE
New Chromium Update Messes Up Background

### ISSUE THREAD

**Issue by Niferu** [ByteGrad/portfolio-website#16]
Hello guys,

I have recently hosted my portfolio and I was using same bacground effect as in this repository, but last chromium update messed it up and I have no idea if we can fix it or if it is chromium bug to fix. I have not changed the code, bg has messed itself after update.

Background before chromium update:

![image](https://github.com/ByteGrad/portfolio-website/assets/110537615/a055364f-97e6-4821-9acb-f42f539e7eff)

Background after chromium update:

![image](https://github.com/ByteGrad/portfolio-website/assets/110537615/f9382679-43b4-4b5d-bcee-c9539984937a)

As you can see there are barely lines visible on background now. It comes from blur effect added to background while mixing those. Does anyone have any idea how to fix that? @ByteGrad maybe you got some smart trick to get that working?

My code:

```js
    return (
        <html lang="en" className="!scroll-smooth">
            <body className={`${montserrat.className} pt-28 sm:pt-36 bg-gray-300 dark:bg-devil`}>
                <div className="bg-[#fbe2e3] dark:bg-[#671f91a8] absolute top-[1rem] -z-10 right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem]"></div>
                <div className="bg-[#dbd7fb] dark:bg-[#48457c] absolute top-[9rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem]"></div>

                <ThemeContextProvider>
                    <ActiveSectionContextProvider>
                        <Header />
                        {children}
                        <Footer />

                        <Toaster
                            position="top-right"
                            containerStyle={{
                                top: "5rem",
                            }}
                        />
                        <ThemeSwitch />
                    </ActiveSectionContextProvider>
                </ThemeContextProvider>
            </body>
        </html>
    )
```

**Comment by Niferu** [comment]
Semms like it got confirmed as real bug and should be fixed in incoming update: [LINK](https://bugs.chromium.org/p/chromium/issues/detail?id=1500021)

**Comment by Kapil619** [comment]
> Semms like it got confirmed as real bug and should be fixed in incoming update: [LINK](https://bugs.chromium.org/p/chromium/issues/detail?id=1500021)


I finished my portfolio today and I'm having the same issue . Did you find any workaround?  @Nlferu 
![portfolio-error](https://github.com/ByteGrad/portfolio-website/assets/84692375/ce6c64bd-9690-431f-96cc-cff91b01951c)

**Comment by royshemtov13** [comment]
I have the same issue here as well

**Comment by royshemtov13** [comment]
adding the code below to each div will fix the issue
style={{ transform: "translate3d(0,0,0)" }}

```jsx
        <div
          style={{ transform: "translate3d(0,0,0)" }}
        className="bg-[#fbe2e3] absolute top-[-6rem] -z-10 right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] sm:w-[68.75rem] dark:bg-[#946263]"
        ></div>
        <div
          style={{ transform: "translate3d(0,0,0)" }}
          className="bg-[#dbd7fb] absolute top-[-1rem] -z-10 left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]"
        ></div>
```

**Comment by Kapil619** [comment]
> ```js
>  style={{ transform: "translate3d(0,0,0)" }}
> ```

Thanks , That fixed the issue for me !🫡

**Comment by Niferu** [comment]
WOOOW @royshemtov13  thaaanks a lot!! It was driving me crazy! How did you figured out solution to this one?

**Comment by royshemtov13** [comment]
@Nlferu 
With just trial and error haha and than this worked, it is something with the chromium update that to my knowledge it overides the 3d area around it. Once the chromium update is fixed you can revert back to the same code as before I think.

**Comment by Niferu** [comment]
Thanks a lot @royshemtov13 !!!

You are truly amazing for solving this issue, cheers and best of luck for you mate!! :D
